### ISSUE TITLE
SVG format doesn’t work

### ISSUE THREAD

**Issue by dan0102dan** [izonder/imagemagick-convert#4]
I convert to svg, but get an empty Buffer

**Comment by izonder** [comment]
What should I do with the information above? With specified pre-requisites it is working fine.

Provide at least:
- Node.js version
- Imagemagick version
- which OS
- logs entries

**Comment by dan0102dan** [comment]
Node Js: v14.4.0
Imagemagick version: 7.0.10-27
Ububntu 18.04
base64 code (this image in png works)

**Comment by dan0102dan** [comment]
do you have social networks, can we contact directly?

**Comment by dan0102dan** [comment]
So and what??
